insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("notebook", "Electronic products", 100, "Samsung", 20, "for game")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("desktop computer", "Electronic products", 150, "Samsung", 10, "For office")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("TV", "Electronic products", 300, "LG", 200, "QLED")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("SmartPhone", "Electronic products", 200, "Samsung", 20, "new")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("lip balm", "cosmetics", 10, "Kiehl", 100, "Cranberry")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("hand cream", "cosmetics", 15, "TonyMory", 100, "Cranberry")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("Powder", "cosmetics", 20, "TonyMory", 50, "Cotton")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("Correction Paper", "Stationery products", 5, "Morning Glory", 500, "Sky blue")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("Pen", "Stationery products", 3, "Morning Glory", 500, "Red")
insert into producttable(name, category, price, manufacturer, unit_in_stock, description) values ("GlassDeco", "Stationery products", 50, "Morning Glory", 10, "for Infant")